# --------------------------------------------------
# Background
# --------------------------------------------------

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    noise = 0.0117
    contrast = 1.1
    brightness = 0.8
    vibrancy = 0.18
    vibrancy_darkness = 0.0
}

# --------------------------------------------------
# Clock
# --------------------------------------------------

label {
    monitor =
    text = $TIME
    font_family = Inter
    font_size = 72
    color = rgba(cdd6f4ff)

    position = 0, 170
    halign = center
    valign = center
}

# --------------------------------------------------
# Date
# --------------------------------------------------

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    font_family = Inter
    font_size = 22
    color = rgba(a6adc8ff)

    position = 0, 110
    halign = center
    valign = center
}

# --------------------------------------------------
# Password Box
# --------------------------------------------------

input-field {
    monitor =

    size = 320, 56

    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.25

    outer_color = rgba(89b4faff)
    inner_color = rgba(1e1e2ecc)

    font_color = rgba(cdd6f4ff)

    placeholder_text = Password...

    rounding = 12

    fade_on_empty = false

    position = 0, -40
    halign = center
    valign = center
}
